package com.example.medicineexpiryapp;

import android.graphics.Bitmap;
import android.os.Bundle;
import android.provider.MediaStore;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

public class DisplayQRActivity extends AppCompatActivity {

    public static Bitmap bitmapQRCode; // Bitmap passed from GenerateActivity

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_display_qractivity);

        ImageView qrImage = findViewById(R.id.qr_image);
        Button btnSave = findViewById(R.id.btn_save_qr);
        Button btnCancel = findViewById(R.id.btn_cancel_qr);

        if (bitmapQRCode != null) {
            qrImage.setImageBitmap(bitmapQRCode);
        }

        btnSave.setOnClickListener(v -> saveToGallery(bitmapQRCode));
        btnCancel.setOnClickListener(v -> finish());
    }

    private void saveToGallery(Bitmap bitmap) {
        try {
            String savedURL = MediaStore.Images.Media.insertImage(
                    getContentResolver(),
                    bitmap,
                    "QR_Code_" + System.currentTimeMillis(),
                    "Generated by MedicineExpiryApp"
            );

            if (savedURL != null) {
                Toast.makeText(this, "Saved to gallery!", Toast.LENGTH_SHORT).show();
            } else {
                Toast.makeText(this, "Failed to save", Toast.LENGTH_SHORT).show();
            }
        } catch (Exception e) {
            e.printStackTrace();
            Toast.makeText(this, "Error saving QR", Toast.LENGTH_SHORT).show();
        }
    }
}
